language: go
go:
  - 1.2
  - 1.3
  - tip
env: PATH=$GOPATH/bin:$PATH
install:
  - go get github.com/nitrous-io/goop
  - make install-deps
script: make test
after_script: goop exec goveralls -repotoken Qmbg1eGELC9QLg1iV1CG3yHWCtYTe5iJn ./cli
